<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>E-Safe School - Beranda</title>
<style>
:root{--blue-900:#1e3a8a;--blue-800:#1e40af;--blue-700:#1d4ed8;--blue-100:#dbeafe;--slate-50:#f8fafc;--gray-100:#f3f4f6;--gray-300:#d1d5db;--gray-400:#9ca3af;--gray-500:#6b7280;--gray-600:#4b5563;--gray-800:#1f2937;--gray-900:#111827}
*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:var(--gray-900);background:#fff}a{text-decoration:none;color:inherit}.container{max-width:1200px;margin:0 auto;padding:0 24px}
.navbar{background:#fff;border-bottom:1px solid var(--gray-100)}.navbar .container{display:flex;align-items:center;justify-content:space-between;padding-top:16px;padding-bottom:16px}.nav-left{display:flex;align-items:center;gap:16px}.menu-btn{display:flex;color:var(--gray-800);background:none;border:0;cursor:pointer}.brand{display:flex;align-items:center;gap:8px}.brand-icon{height:36px;width:36px;display:flex;align-items:center;justify-content:center;flex-shrink:0;border-radius:50%;background:var(--blue-900)}.brand-name{color:var(--gray-900);font-size:16px;font-weight:700}.nav-links{display:flex;align-items:center;gap:32px;font-size:14px;font-weight:600}.nav-links a{color:var(--gray-600)}.nav-links a.active,.nav-links a:hover{color:var(--blue-700)}
.hero{background:var(--slate-50)}.hero .container{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:center;padding-top:64px;padding-bottom:64px}.badge{display:inline-flex;align-items:center;gap:8px;padding:6px 14px;margin-bottom:20px;border-radius:999px;background:var(--blue-100);color:var(--blue-700);font-size:12px;font-weight:600}.hero h1{margin-bottom:16px;color:var(--blue-900);font-size:44px;font-weight:800;line-height:1.2}.hero p{max-width:420px;margin-bottom:32px;color:var(--gray-500);font-size:15px}.btn-group{display:flex;flex-wrap:wrap;gap:12px}.btn{padding:12px 24px;border:1px solid transparent;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;transition:background .15s ease}.btn-primary{background:var(--blue-900);color:#fff}.btn-primary:hover{background:var(--blue-800)}.btn-outline{border-color:var(--gray-300);background:#fff;color:var(--gray-800)}.btn-outline:hover{background:var(--gray-100)}.hero-illustration{display:flex;justify-content:center}.hero-illustration img{display:block;width:100%;max-width:420px;height:auto;object-fit:contain}
.stats{border-top:1px solid var(--gray-100);background:#fff}.stats .container{display:grid;grid-template-columns:repeat(3,1fr);gap:40px;padding-top:56px;padding-bottom:56px}.stat-item{display:flex;align-items:center;gap:16px}.stat-icon{height:56px;width:56px;display:flex;align-items:center;justify-content:center;flex-shrink:0;border-radius:16px;background:var(--blue-100)}.stat-number{color:var(--gray-900);font-size:24px;font-weight:800}.stat-label{color:var(--gray-800);font-size:14px;font-weight:600}.stat-desc{color:var(--gray-400);font-size:12px}
@media(max-width:768px){.nav-links{display:none}.nav-links.is-open{display:flex;position:absolute;top:68px;left:0;right:0;z-index:2;flex-direction:column;align-items:flex-start;gap:16px;padding:16px 24px;border-bottom:1px solid var(--gray-100);background:#fff}.hero .container{grid-template-columns:1fr;text-align:center}.hero p{margin-right:auto;margin-left:auto}.btn-group{justify-content:center}.stats .container{grid-template-columns:1fr;gap:32px}}
</style>
</head>
<body>
<nav class="navbar"><div class="container"><div class="nav-left"><button class="menu-btn" id="menuBtn" type="button" aria-label="Menu" aria-expanded="false"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><a href="{{ url('/') }}" class="brand"><span class="brand-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></span><span class="brand-name">E-Safe School</span></a></div><div class="nav-links"><a href="{{ url('/') }}" class="active">Beranda</a><a href="{{ url('/lost-and-found') }}">Lost &amp; Found</a><a href="{{ url('/pengaduan') }}">Pengaduan</a></div></div></nav>
<section class="hero"><div class="container"><div class="hero-text"><span class="badge"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>E-Safe School</span><h1>Sekolah Aman, Nyaman,<br>dan Peduli</h1><p>Platform pengaduan dan lost &amp; found untuk mewujudkan lingkungan sekolah yang aman, nyaman, dan saling peduli</p><div class="btn-group"><a href="{{ url('/pengaduan/lapor') }}" class="btn btn-primary">Laporkan Pengaduan</a><a href="{{ url('/lost-and-found/lapor') }}" class="btn btn-outline">Laporkan Lost &amp; Found</a></div></div><div class="hero-illustration"><img src="{{ asset('assets/Foto Anak Sekolah.png') }}" alt="Ilustrasi siswa E-Safe School"></div></div></section>
<section class="stats"><div class="container"><div class="stat-item"><div class="stat-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#1d4ed8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 10h.01M12 10h.01M16 10h.01M21 12c0 4.418-4.03 8-9 8-1.06 0-2.077-.163-3.02-.463L3 21l1.5-4.5C3.55 15.163 3 13.62 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg></div><div><p class="stat-number">{{ $totalPengaduan ?? 120 }}</p><p class="stat-label">Pengaduan</p><p class="stat-desc">Total Laporan Masuk</p></div></div><div class="stat-item"><div class="stat-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#1d4ed8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg></div><div><p class="stat-number">{{ $totalBarang ?? 85 }}</p><p class="stat-label">Barang Ditemukan</p><p class="stat-desc">Barang yang Berhasil Ditemukan</p></div></div><div class="stat-item"><div class="stat-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#1d4ed8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></div><div><p class="stat-number">{{ $totalSelesai ?? 95 }}</p><p class="stat-label">Kasus Selesai</p><p class="stat-desc">Laporan yang Telah Diselesaikan</p></div></div></div></section>
<script>document.getElementById('menuBtn').addEventListener('click',function(){const links=document.querySelector('.nav-links');const open=links.classList.toggle('is-open');this.setAttribute('aria-expanded',open)});</script>
</body>
</html>
